import { AnchorViewpoint } from "../types/viewer";

export const TOTAL_FRAMES = 120;

/** Frame shown on first load / reset (Anchor View 01). */
export const INITIAL_FRAME = 10;

/**
 * Two quality tiers generated by `scripts/build-frames.mjs`:
 *  - "lq": 960x540 WebP (~30-60 KB) -> preloaded for every frame, used for instant paint & fast drag
 *  - "hq": 2560x1440 WebP           -> streamed only around the current viewpoint (bounded cache)
 */
export type FrameTier = "lq" | "hq";

export const FRAME_BASE_PATH = "/frames";

export const OFFICIAL_ANCHOR_FRAMES: readonly number[] = [10, 30, 50, 70, 90, 110] as const;

export const ANCHOR_VIEWPOINTS: AnchorViewpoint[] = [
  {
    id: 1,
    frame: 10,
    label: "View 01",
    name: "North Grand Plaza",
    azimuthDeg: 27,
    description: "Main arrival boulevard, architectural canopy and public square",
  },
  {
    id: 2,
    frame: 30,
    label: "View 02",
    name: "East Waterfront & Marina",
    azimuthDeg: 87,
    description: "Pedestrian promenade, private docks and sunrise aspect",
  },
  {
    id: 3,
    frame: 50,
    label: "View 03",
    name: "Central Courtyard & Atrium",
    azimuthDeg: 147,
    description: "Heart of the development with sunken gardens and light wells",
  },
  {
    id: 4,
    frame: 70,
    label: "View 04",
    name: "South Gateway & Commercial",
    azimuthDeg: 207,
    description: "Retail boulevard, flagship stores and transit connection",
  },
  {
    id: 5,
    frame: 90,
    label: "View 05",
    name: "West Botanical Terraces",
    azimuthDeg: 267,
    description: "Cascading residential rooftop greenery and sunset vista",
  },
  {
    id: 6,
    frame: 110,
    label: "View 06",
    name: "Skyline Vista & High-Rise",
    azimuthDeg: 327,
    description: "Full architectural elevation overlooking the metropolitan skyline",
  },
];

/**
 * Normalizes any frame number (including float and negative) into the continuous [1, totalFrames] circular range.
 */
export function wrapFrame(frame: number, totalFrames: number = TOTAL_FRAMES): number {
  const norm = ((frame - 1) % totalFrames + totalFrames) % totalFrames;
  return norm + 1;
}

/**
 * Calculates the shortest signed circular distance from f1 to f2.
 * Positive returned value means clockwise (forward), negative means counter-clockwise.
 * Range: [-totalFrames/2, +totalFrames/2]
 */
export function circularDistance(f1: number, f2: number, totalFrames: number = TOTAL_FRAMES): number {
  const delta = f2 - f1;
  const half = totalFrames / 2;
  return ((delta + half) % totalFrames + totalFrames) % totalFrames - half;
}

/**
 * Calculates absolute circular distance between two frames.
 */
export function absCircularDistance(f1: number, f2: number, totalFrames: number = TOTAL_FRAMES): number {
  return Math.abs(circularDistance(f1, f2, totalFrames));
}

/**
 * Rounds any (float / negative / overflowing) frame value to an integer frame index in [1, totalFrames].
 * Note: Math.round(wrapFrame(x)) alone can yield totalFrames + 1 (e.g. 120.6 -> 121), so we wrap after rounding.
 */
export function toFrameIndex(frame: number, totalFrames: number = TOTAL_FRAMES): number {
  return wrapFrame(Math.round(frame), totalFrames);
}

/**
 * Converts a frame number (1-120) to azimuth degrees (0° to 357°).
 */
export function frameToAzimuth(frame: number, totalFrames: number = TOTAL_FRAMES): number {
  const wrapped = wrapFrame(frame, totalFrames);
  const deg = ((wrapped - 1) / totalFrames) * 360;
  return Math.round(deg * 10) / 10;
}

/**
 * Finds the nearest predefined anchor viewpoint to a given frame.
 */
export function findNearestAnchor(
  frame: number,
  anchors: readonly number[] = OFFICIAL_ANCHOR_FRAMES,
  totalFrames: number = TOTAL_FRAMES
): {
  anchorFrame: number;
  viewpoint: AnchorViewpoint | null;
  signedDistance: number;
  absDistance: number;
} {
  let minAbsDist = Infinity;
  let bestAnchor = anchors[0];
  let bestSigned = 0;

  for (const anchor of anchors) {
    const signed = circularDistance(frame, anchor, totalFrames);
    const abs = Math.abs(signed);
    if (abs < minAbsDist) {
      minAbsDist = abs;
      bestAnchor = anchor;
      bestSigned = signed;
    }
  }

  const viewpoint = ANCHOR_VIEWPOINTS.find((v) => v.frame === bestAnchor) || null;

  return {
    anchorFrame: bestAnchor,
    viewpoint,
    signedDistance: bestSigned,
    absDistance: minAbsDist,
  };
}

/**
 * Smooth cubic easing out: fast start, soft deceleration.
 */
export function easeOutCubic(t: number): number {
  return 1 - Math.pow(1 - t, 3);
}

/**
 * Smooth quartic easing out.
 */
export function easeOutQuart(t: number): number {
  return 1 - Math.pow(1 - t, 4);
}

/**
 * Resolves the URL of a frame (1-120) for the requested quality tier, e.g. frame 7 -> /frames/hq/007.webp
 */
export function getFrameUrl(frame: number, tier: FrameTier): string {
  const index = toFrameIndex(frame);
  return `${FRAME_BASE_PATH}/${tier}/${String(index).padStart(3, "0")}.webp`;
}


